
[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Regular"

[keyboard]
bindings = [
# { chars = '\p', key = "LBracket", mods = "Command" },
# { chars = '\n', key = "RBracket", mods = "Command" },
# { chars = "\u001E", key = "Key6", mods = "Control" },
{ key = "t", mods = "Control", action = "CreateNewTab" },
]

[window]
opacity = 1.0

[general]
live_config_reload = true

import = ["~/.config/alacritty/tokyo-night-storm.toml",]
